services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: gestor_claves
      MYSQL_USER: erik
      MYSQL_PASSWORD: pass123

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 10

  nodeapp:
    build: .
    container_name: node_app

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      DB_HOST: mysql
      DB_USER: erik
      DB_PASSWORD: pass123
      DB_NAME: gestor_claves

    ports:
      - "3000:3000"

volumes:
  mysql_data: